
[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"

#[window]
#decorations = "none"

[window.padding]
x = 7
y = 0

[general]
import = ["/Users/daniel/.config/alacritty/catppuccin-mocha.toml"]

