import = ["/Users/mischa/.config/alacritty/catppuccin-mocha.toml"]

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

#[window]
#decorations = "none"

[window.padding]
x = 7
y = 0
